v1.1.0 (#32)
* update values (#1)

* Release/1 0 1 (#3)

* update values

* update jobs

* Release/1 0 1 (#4)

* update values

* update jobs

* update deploy

* Release/1 0 1 (#5)

* update values

* update jobs

* update deploy

* update env for runner

* Release/1 0 1 (#7)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* Release/1 0 1 (#9)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* Release/1 0 1 (#10)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* Release/1 0 1 (#11)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* Release/1 0 1 (#13)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* Release/1 0 1 (#14)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* Release/1 0 1 (#15)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* Release/1 0 1 (#16)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* Release/1 0 1 (#17)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* set context

* Release/1 0 1 (#18)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* set context

* configure kubeconfig

* Release/1 0 1 (#19)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* set context

* configure kubeconfig

* update runs on

* Release/1 0 1 (#20)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* set context

* configure kubeconfig

* update runs on

* update kubectl

* Release/1 0 1 (#21)

* update values

* update jobs

* update deploy

* update env for runner

* use source

* update source

* update scripts call

* update deploy

* update chmod

* update deploy

* printenv

* add secrets

* set context

* configure kubeconfig

* update runs on

* update kubectl

* update deploy

* remove kind (#24)

* Release/1 0 2 (#25)

* remove kind

* remove kind cmd

* rm prod job (#27)

* Release/1 0 3 (#28)

* rm prod job

* install helm

* update deploy (#29)

* add design to dev (#31)

* update readme and values

* update readme and create-env.sh

* update create-env

* update .gitignore

* rm kubectl download

* update .gitignore

diff --git a/.github/workflows/deploy-dev-qa.yml b/.github/workflows/deploy-dev-qa.yml
--- a/.github/workflows/deploy-dev-qa.yml
+++ b/.github/workflows/deploy-dev-qa.yml
@@ -1,9 +1,13 @@
+
 name: Deploy Flowable Platform
 
 on:
   push:
     branches:
       - dev
+      - main
+    tags:
+      - 'v*.*.*'
 
 jobs:
   setup:
@@ -21,23 +25,14 @@ jobs:
           chmod +x kubectl
           # Move the binary to a directory in your system's PATH
           sudo mv ./kubectl /usr/local/bin/kubectl
-      # - name: Install kind
-      #   run: |
-      #     curl -Lo ./kind "https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64"
-      #     chmod +x ./kind
-      #     sudo mv ./kind /usr/local/bin/kind
-      - name: Verify kind and kubectl
-        run: |
-          # kind --version
-          kubectl version --client
       - name: Set kubeconfig output
         id: set-kubeconfig
         run: echo "kubeconfig-path=$HOME/.kube/config" >> $GITHUB_OUTPUT
 
   deploy-dev-qa:
     needs: setup
-    runs-on: [self-hosted]
-    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
+    runs-on: [self-hosted, qa]
+    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/dev' }}
     steps:
       - uses: actions/checkout@v4
 
@@ -69,24 +64,38 @@ jobs:
           FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
           FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
 
-  # deploy-stg-prod:
-  #   needs: setup
-  #   runs-on: [self-hosted]
-  #   if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
-  #   steps:
-  #     - name: Checkout repository
-  #       uses: actions/checkout@v4
-  #     - name: Use kind kubeconfig for prod cluster
-  #       run: |
-  #         export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
-  #         kubectl config use-context kind-prod || echo "Context prod not found - this job assumes cluster already set."
-  #     - name: Run deploy-flowable-platform.sh for stg/prod
-  #       run: |
-  #         cd $GITHUB_WORKSPACE
-  #         git submodule update --init --recursive --remote --force
-  #         sudo chmod a+x $GITHUB_WORKSPACE/scripts/*
-  #         source "$GITHUB_WORKSPACE/scripts/deploy-flowable-platform.sh" "stg" "flowable" "prod"
-  #       env:
-  #         FLOWABLE_LICENSE_KEY: ${{ secrets.FLOWABLE_LICENSE_KEY }}
-  #         FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
-  #         FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
+
+  deploy-tagged-release:
+    needs: setup
+    runs-on: [self-hosted, prod]
+    if: ${{ startsWith(github.ref, 'refs/tags/v') && github.ref_name != '' && github.ref_type == 'tag' && github.event.base_ref == 'refs/heads/main' }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install kubectl and helm
+        uses: azure/setup-kubectl@v4
+        with:
+          version: 'v1.30.0'
+
+      - name: Show cluster nodes (in-cluster auth)
+        run: |
+          API="https://kubernetes.default.svc"
+          TOKEN="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
+          CA="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
+          kubectl --server="${API}" --token="${TOKEN}" --certificate-authority="${CA}" get pods -A
+
+      - name: Use kind kubeconfig for prod cluster
+        run: |
+          export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
+          kubectl config use-context kind-prod || echo "Context prod not found - this job assumes cluster already set."
+      - name: Run deploy-flowable-platform.sh for tagged release
+        run: |
+          cd $GITHUB_WORKSPACE
+          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+          git submodule update --init --recursive --remote --force
+          sudo chmod a+x $GITHUB_WORKSPACE/scripts/*
+          source "$GITHUB_WORKSPACE/scripts/deploy-flowable-platform.sh" "stg" "flowable" "prod"
+        env:
+          FLOWABLE_LICENSE_KEY: ${{ secrets.FLOWABLE_LICENSE_KEY }}
+          FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
+          FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
