rm prod job

diff --git a/.github/workflows/deploy-dev-qa.yml b/.github/workflows/deploy-dev-qa.yml
--- a/.github/workflows/deploy-dev-qa.yml
+++ b/.github/workflows/deploy-dev-qa.yml
@@ -76,24 +76,24 @@ jobs:
           FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
           FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
 
-  deploy-stg-prod:
-    needs: setup
-    runs-on: [self-hosted]
-    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Use kind kubeconfig for prod cluster
-        run: |
-          export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
-          kubectl config use-context kind-prod || echo "Context prod not found - this job assumes cluster already set."
-      - name: Run deploy-flowable-platform.sh for stg/prod
-        run: |
-          cd $GITHUB_WORKSPACE
-          git submodule update --init --recursive --remote --force
-          sudo chmod a+x $GITHUB_WORKSPACE/scripts/*
-          source "$GITHUB_WORKSPACE/scripts/deploy-flowable-platform.sh" "stg" "flowable" "prod"
-        env:
-          FLOWABLE_LICENSE_KEY: ${{ secrets.FLOWABLE_LICENSE_KEY }}
-          FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
-          FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
+  # deploy-stg-prod:
+  #   needs: setup
+  #   runs-on: [self-hosted]
+  #   if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
+  #     - name: Use kind kubeconfig for prod cluster
+  #       run: |
+  #         export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
+  #         kubectl config use-context kind-prod || echo "Context prod not found - this job assumes cluster already set."
+  #     - name: Run deploy-flowable-platform.sh for stg/prod
+  #       run: |
+  #         cd $GITHUB_WORKSPACE
+  #         git submodule update --init --recursive --remote --force
+  #         sudo chmod a+x $GITHUB_WORKSPACE/scripts/*
+  #         source "$GITHUB_WORKSPACE/scripts/deploy-flowable-platform.sh" "stg" "flowable" "prod"
+  #       env:
+  #         FLOWABLE_LICENSE_KEY: ${{ secrets.FLOWABLE_LICENSE_KEY }}
+  #         FLOWABLE_REPO_USER: ${{ secrets.FLOWABLE_REPO_USER }}
+  #         FLOWABLE_REPO_PASSWORD: ${{ secrets.FLOWABLE_REPO_PASSWORD }}
