Release/1 0 1 (#2)
* update values

* update jobs

diff --git a/.github/workflows/deploy-dev-qa.yml b/.github/workflows/deploy-dev-qa.yml
--- a/.github/workflows/deploy-dev-qa.yml
+++ b/.github/workflows/deploy-dev-qa.yml
@@ -1,4 +1,3 @@
-jobs:
 name: Deploy Flowable Platform
 
 on:
@@ -6,7 +5,7 @@ on:
     branches:
       - dev
 
-
+jobs:
   setup:
     runs-on: ubuntu-latest
     if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
@@ -42,7 +41,7 @@ on:
       - name: Use kind kubeconfig for qa cluster
         run: |
           export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
-          kubectl config use-context qa || echo "Context qa not found - this job assumes cluster already set."
+          kubectl config use-context kind-qa || echo "Context qa not found - this job assumes cluster already set."
       - name: Run deploy-flowable-platform.sh for dev/qa
         run: scripts/deploy-flowable-platform.sh dev flowable qa
 
@@ -56,6 +55,6 @@ on:
       - name: Use kind kubeconfig for prod cluster
         run: |
           export KUBECONFIG="${{ needs.setup.outputs.kubeconfig-path }}"
-          kubectl config use-context prod || echo "Context prod not found - this job assumes cluster already set."
+          kubectl config use-context kind-prod || echo "Context prod not found - this job assumes cluster already set."
       - name: Run deploy-flowable-platform.sh for stg/prod
         run: scripts/deploy-flowable-platform.sh stg flowable prod
